<a href="<?= URL_APP ?>clientes/" class="back btn btn-outline-success">Regresar</a>


<?= Form::openMultipart() ?>

<div class="container mt-4">
    <div class="row justify-content-center">
        <div class="col-md-6 col-lg-5">
            <div class="card p-4 shadow-sm">
                <h4 class="text-center mb-4">Registro de cliente</h4>
                <h5 class="text-danger"><?= View::content() ?></h5>

                <?= Form::open() ?>

                <div class="mb-3">
                    <label class="form-label">Nombre</label>
                    <?= Form::text('cliente.nombre', 'placeholder="Ingrese el nombre" class="form-control"') ?>
                </div>

                <?= Form::file('image') ?>
<!--                <input type="file" class="filepond" name="image" accept="image/png, image/jpeg, image/gif" />-->

                <div class="row">
                    <div class="col-7 mb-4">
                        <label class="form-label">Correo</label>
                        <?= Form::text('cliente.email', 'placeholder="Ingrese el correo" class="form-control"') ?>
                    </div>

                    <div class="col-5 mb-4">
                        <label class="form-label">Teléfono</label>
                        <?= Form::text('cliente.telefono', 'placeholder="Ingrese el teléfono" class="form-control"') ?>
                    </div>
                </div>

                <div class="d-flex justify-content-center gap-5">
                    <?= Formbs::btn_limpiar() ?>
                    <?= Formbs::btn_aceptar() ?>
                    <?= Formbs::btn_cancelar() ?>
                </div>

            <?= Form::close() ?>
            </div>
        </div>
    </div>
</div>


