<h1>Ventas</h1>
<a href="#" class="btn btn-outline-success">Registrar <i class="fa-solid fa-pencil"></i></a>

<a href="<?= URL_APP ?>ventas/nueva" class="btn btn-outline-primary">Nueva <i class="fa-solid fa-plus"></i></a>

<style>
    th, td {
        padding: 10px; /* Espacio dentro de las celdas */
        text-align: left; /* Alineación del texto */
        border: 1px solid #ddd; /* Borde para las celdas */
    }
</style>
<table class="table table-striped table-hover myTable">
    <thead>
    <tr>
        <th>ID</th>
        <th>Clientes_ID</th>
        <th>Empleados_ID</th>
        <th>Metodos_pago_ID</th>
        <th>Fecha_de_venta</th>
    </tr>

    </thead>

    <tbody>
    <?php foreach ($ventas as $p): ?>
        <tr>
            <td><?= Html::link("ventas/show/{$p->id}", "Ver", ["title" => "ir a venta", "class" => "btn btn-sm"]) ?></td>
            <td><?= $p->cliente->nombre ?? 'N/D' ?></td>
            <td><?= $p->vendedor->nombre ?? 'N/D' ?></td>
            <td><?= $p->metodo->nombre ?? 'N/D' ?></td>
            <td><?= $p->created_at ?? $p->fecha ?></td>
        </tr>
    <?php endforeach; ?>
    </tbody>


</table>