<a href="<?= URL_APP ?>pagos/nuevo" class="btn btn-outline-success">Regresar</a>
<h1>Total abonado: $<?= number_format($total_a_abonar, 2) ?></h1>
<?php foreach ($ventas_a_pagar as $v): ?>

<?= Flash::show('default', 'flash') ?>


<!--<h1>Total por pagar: $--><?php //=number_format($v->por_pagar)?><!--</h1>-->

<table class="table table-sm table-hover">
    <thead>
    <tr>
        <th>id</th>
        <th>Fecha</th>
        <th>Total</th>
        <th>Abonado</th>
        <th>Por pagar</th>
        <th>Pago de</th>
    </tr>
    </thead>

    <tbody>
        <tr>
            <td><?=$v->id?></td>
            <td><?=$v->created_at?></td>
            <td><?=($v->total)?></td>
            <td><?=($v->total - $v->por_pagar)?></td>
            <td><?=$v->por_pagar?></td>
            <td><?=$v->a_abonar?></td>
        </tr>

    <?php endforeach; ?>

    </tbody>
</table>

<?php if (isset($mostrar_alerta) && $mostrar_alerta): ?>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script>
        Swal.fire({
            toast: false,
            position: 'center',
            icon: 'success',
            title: '¡Abono registrado con éxito!',
            showConfirmButton: false,
            timer: 2000,
            timerProgressBar: true,
            background: 'rgba(40,167,69,0.8)',
            color: 'white'
        });
    </script>
<?php endif; ?>


<!--<script>-->
<!--    setTimeout(() => {-->
<!--        const alert = document.querySelector('.alert');-->
<!--        if (alert) {-->
<!--            alert.classList.remove('show');-->
<!--            alert.classList.add('fade');-->
<!--        }-->
<!--    }, 3000);-->
<!--</script>-->

<style>
    .alert, .flash, .message {
        display: none !important;
    }
</style>
