<div class="row flex flex-row items-start justify-between">
    <div class="col-3">
        <div class="product-title">
<!--            --><?php //=Html::link("productos/show/{$p->id}","Ver",["title"=>"Monstera deliciosa","class"=>"btn btn-sm"])?>
            <a href="/productos/show">Monstera deliciosa</a>
        </div>
        <?= htmlbs::img("producto/1.JPG", "", ["width" => "160px"]) ?>
        <div class="price w-1/3 text-right">
            <strong>$ 450.00</strong>
        </div>
    </div>
    <div class="col-3">
        <div class="product-title">
            <a href="/products/arbol-de-la-abundancia">Zamioculca</a>
        </div>
        <?= htmlbs::img("producto/2.JPG", "", ["width" => "160px"]) ?>
        <div class="price w-1/3 text-right">
            <strong>$ 227.00</strong>
        </div>
    </div>
    <div class="col-3">
        <div class="product-title">
            <a href="/products/arbol-de-la-abundancia">Pachira</a>
        </div>
        <?= htmlbs::img("producto/3.JPG", "", ["width" => "160px"]) ?>
        <div class="price w-1/3 text-right">
            <strong>$ 499.99</strong>
        </div>
    </div>
    <div class="col-3">
        <div class="product-title">
            <a href="/products/arbol-de-la-abundancia">Potus limón</a>
        </div>
        <?= htmlbs::img("producto/4.JPG", "", ["width" => "160px"]) ?>
        <div class="price w-1/3 text-right">
            <strong>$ 499.99</strong>
        </div>
    </div>
</div>