<h1>Productos</h1>
<a href="<?=URL_APP?>productos/registrar" class="btn btn-outline-success">Registrar <i class="fa-solid fa-pencil"></i></a>

<style>
    th, td {
        padding: 10px; /* Espacio dentro de las celdas */
        text-align: left; /* Alineación del texto */
        border: 1px solid #ddd; /* Borde para las celdas */
    }
</style>
<table class="table table-striped table-hover myTable">
    <thead>
    <tr>
        <th>ID</th>
        <th>Nombre</th>
        <th>Precio</th>
        <th>Stock</th>
        <th>Categoría</th>
    </tr>

    </thead>

    <tbody>
    <?php foreach ($productos as $p): ?>
        <tr>
            <td style="width: auto"><?= htmlbs::img("producto/$p->id.JPG", "", ["width" => "130px"]) ?>
                <?=Html::link("productos/show/{$p->id}","Ver",["title"=>"ir a producto","class"=>"btn btn-sm"])?></td>
            <td><a href="<?=URL_APP?>productos/show/<?= $p->id ?>"> <?= $p->nombre?></a> </td>
            <td><?=$p->precio?></td>
            <td><?=$p->stock?></td>
            <td><?=$p->categorias_id?></td>
        </tr>
    <?php endforeach; ?>


    </tbody>

</table>