<a href="<?=URL_APP?>productos/" class="back btn btn-outline-success">Regresar</a>

<div class="container mt-4">
    <div class="row justify-content-center">
        <div class="col-md-6 col-lg-5">
            <div class="card p-4 shadow-sm">
                <h4 class="text-center mb-4">Registro de producto</h4>
                <h5 class="text-danger"><?= View::content() ?></h5>

                <?= Form::open() ?>

                <label class="form-label">Categoría</label>
                <div class="mb-3">
                    <select class="js-example-basic-single" name="categorias">
                        <option value="Interior"> 🏡 Plantas de Interior</option>
                        <option value="Pet Friendly"> 🐾 Plantas Pet Friendly</option>
                        <option value="Exterior"> 🌞 Plantas de Exterior</option>
                        <option value="Decorativas"> 🎍 Plantas Decorativas</option>
                        <option value="Bonsais"> 🌳 Árboles y Bonsáis</option>
                        <option value="Tropicales"> 🌴 Palmeras y Plantas Tropicales</option>
                        <option value="Colgantes"> 🍃 Plantas Colgantes</option>
                        <option value="Sustratos">🌿 Sustratos</option>
                        <option value="abonos">🌱 Abonos</option>
                    </select>
                </div>

                <div class="mb-3">
                    <label class="form-label">Nombre</label>
                    <?= Form::text('producto.nombre', 'placeholder="Ingrese el nombre" class="form-control"') ?>
                </div>

<!--                <input type="file" class="filepond" name="image" accept="image/png, image/jpeg, image/gif" />-->
                <input type="file" name="image" accept="image/*">

                <div class="row">
                    <div class="col-5 mb-4">
                        <label class="form-label">Precio</label>
                        <?= Form::number('producto.precio', 'placeholder="Ingrese el precio" class="form-control" min="0" step="0.01"') ?>
                    </div>

                    <div class="col-6 mb-4">
                        <label class="form-label">Existencias</label>
                        <?= Form::number('producto.stock', 'placeholder="Ingrese la cantidad" class="form-control" min="0" step="1"') ?>
                    </div>
                </div>

                <div class="d-flex justify-content-center gap-5">
                    <?= Formbs::btn_limpiar() ?>
                    <?= Formbs::btn_aceptar() ?>
                    <?= Formbs::btn_cancelar() ?>
                </div>

            <?= Form::close() ?>
            </div>
        </div>
    </div>
</div>

