<?php header('HTTP/1.1 401 Unauthorized') ?>

<?php //echo View::content() ?>

<!DOCTYPE html>
<html lang="en">
<!-- [Head] start -->

<head>
    <title>Login | Mantis Bootstrap 5 Admin Template</title>
    <!-- [Meta] -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="Mantis is made using Bootstrap 5 design framework. Download the free admin template & use it for your project.">
    <meta name="keywords" content="Mantis, Dashboard UI Kit, Bootstrap 5, Admin Template, Admin Dashboard, CRM, CMS, Bootstrap Admin Template">

    <!-- [Favicon] icon -->
    <link rel="icon" href="/kumbiaphp/libs/mantis/dist/assets/images/favicon.svg" type="image/x-icon"> <!-- [Google Font] Family -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Public+Sans:wght@300;400;500;600;700&display=swap" id="main-font-link">
    <!-- [Tabler Icons] https://tablericons.com -->
    <link rel="stylesheet" href="/kumbiaphp/libs/mantis/dist/assets/fonts/tabler-icons.min.css" >
    <!-- [Feather Icons] https://feathericons.com -->
    <link rel="stylesheet" href="/kumbiaphp/libs/mantis/dist/assets/fonts/feather.css" >
    <!-- [Font Awesome Icons] https://fontawesome.com/icons -->
    <link rel="stylesheet" href="/kumbiaphp/libs/mantis/dist/assets/fonts/fontawesome.css" >
    <!-- [Material Icons] https://fonts.google.com/icons -->
    <link rel="stylesheet" href="/kumbiaphp/libs/mantis/dist/assets/fonts/material.css" >
    <!-- [Template CSS Files] -->
    <link rel="stylesheet" href="/kumbiaphp/libs/mantis/dist/assets/css/style.css" id="main-style-link" >
    <link rel="stylesheet" href="/kumbiaphp/libs/mantis/dist/assets/css/style-preset.css" >

</head>

<body>
<!-- [ Pre-loader ] start -->
<div class="loader-bg">
    <div class="loader-track">
        <div class="loader-fill"></div>
    </div>
</div>

<div class="auth-main">
    <div class="auth-wrapper v3">
        <!--      AQUI-->
        <div class="auth-form">
            <div class="auth-header">
                <!--          <img src="page/plantnet-logo.svg" alt="logo">-->
                <!--          <?= htmlbs::img("page/plantnet-logo.svg", "", ["width" => "140px"]) ?>-->
            </div>
            <div class="card my-5">
                <div class="card-body">
                    <div class="d-flex justify-content-between align-items-end mb-4">
                        <h3 class="mb-0"><b>Login</b></h3>
                        <a href="#" class="link-primary">¿No tienes una cuenta?</a>
                    </div>

                    <form method="post">
                        <div class="ui form">
                            <div class="two fields">

                                <div class="field form-group mb-3">
                                    <label class="form-label">Email de usuario</label>
                                    <input class="form-control" placeholder="email" type="email" name="login[email]" value="govani@liz.mx">
                                </div>

                                <div class="field form-group mb-3">
                                    <label class="form-label">Contraseña</label>
                                    <div class="input-group">
                                        <input class="form-control" placeholder="Password" type="password" name="login[password]" id="passwordInput" value="123123">
                                        <button class="btn btn-outline-secondary" type="button" id="togglePassword">
                                            <i class="ti ti-eye" id="iconEye"></i>
                                        </button>
                                    </div>
                                </div>

                                <div class="d-flex mt-1 justify-content-between">
                                    <div class="form-check">
                                        <input class="form-check-input input-primary" type="checkbox" id="customCheckc1" checked="">
                                        <label class="form-check-label text-muted" for="customCheckc1">Recordar contraseña</label>
                                    </div>
                                </div>
                            </div>

                            <div class="d-grid mt-4">
                                <button type="submit" class="ui submit button btn btn-primary">INICIAR SESIÓN</button>
                            </div>
                        </div>
                    </form>


                </div>
            </div>
            <div class="auth-footer row">
                <!-- <div class=""> -->
                <div class="col my-1">
                    <!--              <p class="m-0">Copyright © <a href="#">Codedthemes</a></p>-->
                    <p href='https://wiki.kumbiaphp.com/Team_Development_KumbiaPHP_Framework'>© <?= date('Y'); ?> KumbiaPHP Team</p>
                </div>
                <div class="col-auto my-1">
                    <ul class="list-inline footer-link mb-0">
<!--                        <li class="list-inline-item"><a href="#">Inicio</a></li>-->
                        <!--                <li class="list-inline-item"><a href="#">Privacy Policy</a></li>-->
                        <li class="list-inline-item"><a href="#">Contáctanos</a></li>
                    </ul>
                </div>
                <!-- </div> -->
            </div>
        </div>
    </div>
</div>
<!-- [ Main Content ] end -->
<!-- Required Js -->
<script src="/kumbiaphp/libs/mantis/dist/assets/js/plugins/popper.min.js"></script>
<script src="/kumbiaphp/libs/mantis/dist/assets/js/plugins/simplebar.min.js"></script>
<script src="/kumbiaphp/libs/mantis/dist/assets/js/plugins/bootstrap.min.js"></script>
<script src="/kumbiaphp/libs/mantis/dist/assets/js/fonts/custom-font.js"></script>
<script src="/kumbiaphp/libs/mantis/dist/assets/js/pcoded.js"></script>
<script src="/kumbiaphp/libs/mantis/dist/assets/js/plugins/feather.min.js"></script>

<script>layout_change('light');</script>
<!--  <script>change_box_container('false');</script>-->
<script>layout_rtl_change('false');</script>
<script>preset_change("preset-1");</script>
<script>font_change("Public-Sans");</script>

<script>
    const togglePassword = document.getElementById('togglePassword');
    const passwordInput = document.getElementById('passwordInput');
    const icon = document.getElementById('iconEye');

    togglePassword.addEventListener('click', () => {
        const isPassword = passwordInput.type === 'password';
        passwordInput.type = isPassword ? 'text' : 'password';
        icon.className = isPassword ? 'ti ti-eye-off' : 'ti ti-eye';
    });
</script>


</body>

</html>