<!DOCTYPE html>
<html lang="en">
<!-- [Head] start -->

<head>
    <title>Home | Mantis Bootstrap 5 Admin Template</title>
    <!-- [Meta] -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="Mantis is made using Bootstrap 5 design framework. Download the free admin template & use it for your project.">
    <meta name="keywords" content="Mantis, Dashboard UI Kit, Bootstrap 5, Admin Template, Admin Dashboard, CRM, CMS, Bootstrap Admin Template">
    <meta name="author" content="CodedThemes">

    <!-- [Favicon] icon -->
    <link rel="icon" href="<?=URL_APP?>libs/mantis/dist/assets/images/favicon.svg" type="image/x-icon"> <!-- [Google Font] Family -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Public+Sans:wght@300;400;500;600;700&display=swap" id="main-font-link">
    <!-- [Tabler Icons] https://tablericons.com -->
    <link rel="stylesheet" href="<?=URL_APP?>libs/mantis/dist/assets/fonts/tabler-icons.min.css" >
    <!-- [Feather Icons] https://feathericons.com -->
    <link rel="stylesheet" href="<?=URL_APP?>libs/mantis/dist/assets/fonts/feather.css" >
    <!-- [Font Awesome Icons] https://fontawesome.com/icons -->
    <link rel="stylesheet" href="<?=URL_APP?>libs/mantis/dist/assets/fonts/fontawesome.css" >
    <!-- [Material Icons] https://fonts.google.com/icons -->
    <link rel="stylesheet" href="<?=URL_APP?>libs/mantis/dist/assets/fonts/material.css" >
    <!-- [Template CSS Files] -->
    <link rel="stylesheet" href="<?=URL_APP?>libs/mantis/dist/assets/css/style.css" id="main-style-link" >
    <link rel="stylesheet" href="<?=URL_APP?>libs/mantis/dist/assets/css/style-preset.css" >
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">

    <!--Establecer la integración de JQuery-->
    <!--<script src="kumbiaphp/default/public/libs/JQuery/jquery-3.7.1.min.js"></script>-->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

    <!--Establecer la conexión al DataTables-->
    <link rel="stylesheet" href="https://cdn.datatables.net/2.2.2/css/dataTables.dataTables.css"/>
    <script src="https://cdn.datatables.net/2.2.2/js/dataTables.js"></script>

    <!-- Incluye el CSS de FilePond -->
    <link href="https://unpkg.com/filepond/dist/filepond.min.css" rel="stylesheet">

    <!-- Select2 -->
    <link href="https://cdn.jsdelivr.net/npm/select2@4.0.13/dist/css/select2.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.0.13/dist/js/select2.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>


</head>
<!-- [Head] end -->
<!-- [Body] Start -->

<body data-pc-preset="preset-1" data-pc-direction="ltr" data-pc-theme="light">
<!-- [ Pre-loader ] start -->
<div class="loader-bg">
    <div class="loader-track">
        <div class="loader-fill"></div>
    </div>
</div>
<!-- [ Pre-loader ] End -->
<!-- [ Sidebar Menu ] start -->
<nav class="pc-sidebar">
    <div class="navbar-wrapper">
        <div class="m-header">
<!--            <a href="../dashboard/index.html" class="b-brand text-primary">-->
                <!-- ========   Change your logo from here   ============ -->
                <?= htmlbs::img("page/plantnet-logo.svg", "", ["width" => "140px"]) ?>
<!--                <img src="/kumbiaphp/public/libs/mantis/dist/assets/images/plantnet-logo.svg" class="img-fluid logo-lg" alt="logo">-->
<!--            </a>-->
        </div>
        <div class="navbar-content">
            <ul class="pc-navbar">
                <li class="pc-item">
<!--                    <a href="../dashboard/index.html" class="pc-link">-->
<!--                        <span class="pc-micon"><i class="ti ti-dashboard"></i></span>-->
<!--                        <span class="pc-mtext">Dashboard</span>-->
<!--                    </a>-->
                </li>

<!--                <li class="pc-item pc-caption" style="color: #3da321; font-weight: bold;">-->
<!--                <label><strong>UI Components</strong></label>-->
<!--                    <i class="ti ti-dashboard"></i>-->
<!--                </li>-->
<!--                <li class="pc-item">-->
<!--                    <a href="/kumbiaphp/libs/mantis/dist/elements/bc_typography.html" class="pc-link">-->
<!--                        <span class="pc-micon"><i class="ti ti-typography"></i></span>-->
<!--                        <span class="pc-mtext">Typography</span>-->
<!--                    </a>-->
<!--                </li>-->
<!--                <li class="pc-item">-->
<!--                    <a href="/kumbiaphp/libs/mantis/dist/elements/bc_color.html" class="pc-link">-->
<!--                        <span class="pc-micon"><i class="ti ti-color-swatch"></i></span>-->
<!--                        <span class="pc-mtext">Color</span>-->
<!--                    </a>-->
<!--                </li>-->

                <li class="pc-item pc-caption" style="color: #3da321; font-weight: bold;">
                    <label>Usuarios</label>
                    <i class="ti ti-news"></i>
                </li>
                <li class="pc-item">
<!--                    <a href="/kumbiaphp/default/public/libs/mantis/dist/pages/login.html" class="pc-link">-->
<!--                    <a href="http://localhost:81/kumbiaphp/login/" class="pc-link">-->
<!--                        <span class="pc-micon"><i class="ti ti-lock"></i></span>-->
<!--                        <span class="pc-mtext">Login</span>-->
<!--                    </a>-->
                </li>
                <li class="pc-item">
                    <a href="<?=URL_APP?>clientes/" class="pc-link">
                        <span class="pc-micon"><i class="fa-regular fa-user"></i></span>
                        <span class="pc-mtext">Clientes</span>
                    </a>
                </li>
                <li class="pc-item">
                    <a href="<?=URL_APP?>empleados/" class="pc-link">
                        <span class="pc-micon"><i class="fa fa-user-tie"></i></span>
                        <span class="pc-mtext">Empleados</span>
                    </a>
                </li>

                <li class="pc-item pc-caption" style="color: #3da321; font-weight: bold;">
                    <label>Menú</label>
                    <i class="ti ti-brand-chrome"></i>
                </li>
                <li class="pc-item">
                    <a href="<?=URL_APP?>productos/" class="pc-link">
                        <span class="pc-micon"><i class="ti ti-plant-2"></i></span>
                        <span class="pc-mtext">Productos</span>
                    </a>
                </li>

                <li class="pc-item">
                    <a href="<?=URL_APP?>categorias/" class="pc-link">
                        <span class="pc-micon"><i class="ti ti-plant"></i></span>
                        <span class="pc-mtext">Categorías</span>
                    </a>
                </li>

                <li class="pc-item">
                    <a href="<?=URL_APP?>ventas/" class="pc-link">
                        <span class="pc-micon"><i class="ti ti-shopping-cart"></i></span>
                        <span class="pc-mtext">Ventas</span>
                    </a>
                </li>

                <li class="pc-item">
                    <a href="<?=URL_APP?>detalles/" class="pc-link">
                        <span class="pc-micon"><i class="ti ti-calendar-minus"></i></span>
                        <span class="pc-mtext">Detalles de venta</span>
                    </a>
                </li>

                <li class="pc-item">
                    <a href="<?=URL_APP?>metodos/" class="pc-link">
                        <span class="pc-micon"><i class="ti ti-businessplan"></i></span>
                        <span class="pc-mtext">Métodos de pago</span>
                    </a>
                </li>

                <li class="pc-item">
                    <a href="<?=URL_APP?>pagos/nuevo/" class="pc-link">
                        <span class="pc-micon"><i class="fa-solid fa-coins"></i></span>
                        <span class="pc-mtext">Pagos</span>
                    </a>
                </li>

<!--                <li class="pc-item">-->
<!--                    <a href="--><?php //=URL_APP?><!--/contacto" class="pc-link">-->
<!--                        <span class="pc-micon"><i class="fa-solid fa-coins"></i></span>-->
<!--                        <span class="pc-mtext">Acerca de</span>-->
<!--                    </a>-->
<!--                </li>-->


                <style>
                    /* Cambiar el color de fondo del enlace seleccionado a verde */
                    .pc-item.active .pc-link {
                        background-color: #f1fde5;
                        color: #4afd18;
                    }

                    /* Opcional: Cambiar el color de los iconos */
                    .pc-item.active .pc-micon i {
                        color: green !important;
                        font-weight: bold;
                    }

                    .pc-item.active .pc-mtext{
                        color: green !important;
                        font-weight: bold;
                    }

                    a.pc-link::after {
                        background-color: green !important;
                    }

                </style>
            </ul>

<!--            <div class="card text-center">-->
<!--                <div class="card-body">-->
<!--                    <img src="/kumbiaphp/libs/mantis/dist/assets/images/img-navbar-card.png" alt="images" class="img-fluid mb-2">-->
<!--                    <h5>Upgrade To Pro</h5>-->
<!--                    <p>To get more features and components</p>-->
<!--                    <a href="https://codedthemes.com/item/berry-bootstrap-5-admin-template/" target="_blank"-->
<!--                       class="btn btn-success">Buy Now</a>-->
<!--                </div>-->
<!--            </div>-->

        </div>
    </div>
</nav>
<!-- [ Sidebar Menu ] end --> <!-- [ Header Topbar ] start -->
<header class="pc-header">
    <div class="header-wrapper"> <!-- [Mobile Media Block] start -->
        <div class="me-auto pc-mob-drp">
            <ul class="list-unstyled">
                <!-- ======= Menu collapse Icon ===== -->
                <li class="pc-h-item pc-sidebar-collapse">
                    <a href="#" class="pc-head-link ms-0" id="sidebar-hide">
                        <i class="ti ti-menu-2"></i>
                    </a>
                </li>
                <li class="pc-h-item pc-sidebar-popup">
                    <a href="#" class="pc-head-link ms-0" id="mobile-collapse">
                        <i class="ti ti-menu-2"></i>
                    </a>
                </li>
                <li class="dropdown pc-h-item d-inline-flex d-md-none">
                    <a
                        class="pc-head-link dropdown-toggle arrow-none m-0"
                        data-bs-toggle="dropdown"
                        href="#"
                        role="button"
                        aria-haspopup="false"
                        aria-expanded="false"
                    >
                        <i class="ti ti-search"></i>
                    </a>
                </li>
            </ul>
        </div>
        <!-- [Mobile Media Block end] -->
        <div class="ms-auto">
            <ul class="list-unstyled">
                <li class="dropdown pc-h-item">
                    <a
                        class="pc-head-link dropdown-toggle arrow-none me-0"
                        data-bs-toggle="dropdown"
                        href="#"
                        role="button"
                        aria-haspopup="false"
                        aria-expanded="false"
                    >
                        <i class="ti ti-mail"></i>
                    </a>
                    <div class="dropdown-menu dropdown-notification dropdown-menu-end pc-h-dropdown">
                        <div class="dropdown-header d-flex align-items-center justify-content-between">
                            <h5 class="m-0">Message</h5>
                            <a href="#!" class="pc-head-link bg-transparent"><i class="ti ti-x text-danger"></i></a>
                        </div>
                        <div class="dropdown-divider"></div>
                        <div class="dropdown-header px-0 text-wrap header-notification-scroll position-relative" style="max-height: calc(100vh - 215px)">
                            <div class="list-group list-group-flush w-100">
                                <a class="list-group-item list-group-item-action">
                                    <div class="d-flex">
                                        <div class="flex-shrink-0">
                                            <img src="<?=URL_APP?>libs/mantis/dist/assets/images/user/avatar-2.jpg" alt="user-image" class="user-avtar">
                                        </div>
                                        <div class="flex-grow-1 ms-1">
                                            <span class="float-end text-muted">3:00 AM</span>
                                            <p class="text-body mb-1">It's <b>Cristina danny's</b> birthday today.</p>
                                            <span class="text-muted">2 min ago</span>
                                        </div>
                                    </div>
                                </a>
                                <a class="list-group-item list-group-item-action">
                                    <div class="d-flex">
                                        <div class="flex-shrink-0">
                                            <img src="<?=URL_APP?>libs/mantis/dist/assets/images/user/avatar-1.jpg" alt="user-image" class="user-avtar">
                                        </div>
                                        <div class="flex-grow-1 ms-1">
                                            <span class="float-end text-muted">6:00 PM</span>
                                            <p class="text-body mb-1"><b>Aida Burg</b> commented your post.</p>
                                            <span class="text-muted">5 August</span>
                                        </div>
                                    </div>
                                </a>
                                <a class="list-group-item list-group-item-action">
                                    <div class="d-flex">
                                        <div class="flex-shrink-0">
                                            <img src="<?=URL_APP?>libs/mantis/dist/assets/images/user/avatar-3.jpg" alt="user-image" class="user-avtar">
                                        </div>
                                        <div class="flex-grow-1 ms-1">
                                            <span class="float-end text-muted">2:45 PM</span>
                                            <p class="text-body mb-1"><b>There was a failure to your setup.</b></p>
                                            <span class="text-muted">7 hours ago</span>
                                        </div>
                                    </div>
                                </a>
                                <a class="list-group-item list-group-item-action">
                                    <div class="d-flex">
                                        <div class="flex-shrink-0">
                                            <img src="<?=URL_APP?>libs/mantis/dist/assets/images/user/avatar-4.jpg" alt="user-image" class="user-avtar">
                                        </div>
                                        <div class="flex-grow-1 ms-1">
                                            <span class="float-end text-muted">9:10 PM</span>
                                            <p class="text-body mb-1"><b>Cristina Danny </b> invited to join <b> Meeting.</b></p>
                                            <span class="text-muted">Daily scrum meeting time</span>
                                        </div>
                                    </div>
                                </a>
                            </div>
                        </div>
                        <div class="dropdown-divider"></div>
                        <div class="text-center py-2">
                            <a href="#!" class="link-primary">View all</a>
                        </div>
                    </div>
                </li>
                <li class="dropdown pc-h-item header-user-profile">
                    <a
                        class="pc-head-link dropdown-toggle arrow-none me-0"
                        data-bs-toggle="dropdown"
                        href="#"
                        role="button"
                        aria-haspopup="false"
                        data-bs-auto-close="outside"
                        aria-expanded="false"
                    >
                        <img src="<?=URL_APP?>libs/mantis/dist/assets/images/user/avatar-2.jpg" alt="user-image" class="user-avtar">
                        <span>Acerca de</span>
                    </a>
                    <div class="dropdown-menu dropdown-user-profile dropdown-menu-end pc-h-dropdown">
                        <div class="dropdown-header">
                            <div class="d-flex mb-1">
                                <div class="flex-shrink-0">
                                    <img src="<?=URL_APP?>libs/mantis/dist/assets/images/user/avatar-1.jpg" alt="user-image" class="user-avtar wid-35">
                                </div>
                                <div class="flex-grow-1 ms-3">
                                    <h6 class="mb-1">Yara Juárez Gómez</h6>
                                    <span>Estudiante</span>
                                </div>
                                <a href="#!" class="pc-head-link bg-transparent"><i class="ti ti-power text-danger"></i></a>
                            </div>
                        </div>
                        <ul class="nav drp-tabs nav-fill nav-tabs" id="mydrpTab" role="tablist">
                            <li class="nav-item" role="presentation">
                                <button
                                    class="nav-link active"
                                    id="drp-t1"
                                    data-bs-toggle="tab"
                                    data-bs-target="#drp-tab-1"
                                    type="button"
                                    role="tab"
                                    aria-controls="drp-tab-1"
                                    aria-selected="true"
                                ><i class="ti ti-user"></i> Profile</button
                                >
                            </li>
                            <li class="nav-item" role="presentation">
                                <button
                                    class="nav-link"
                                    id="drp-t2"
                                    data-bs-toggle="tab"
                                    data-bs-target="#drp-tab-2"
                                    type="button"
                                    role="tab"
                                    aria-controls="drp-tab-2"
                                    aria-selected="false"
                                ><i class="ti ti-settings"></i> Setting</button
                                >
                            </li>
                        </ul>
                        <div class="tab-content" id="mysrpTabContent">
                            <div class="tab-pane fade show active" id="drp-tab-1" role="tabpanel" aria-labelledby="drp-t1" tabindex="0">
                                <a href="#!" class="dropdown-item">
                                    <i class="ti ti-edit-circle"></i>
                                    <span>Carrera: ISC</span>
                                </a>
                                <a href="#!" class="dropdown-item">
                                    <i class="ti ti-user"></i>
                                    <span>Materia: Programación Web</span>
                                </a>
                                <a href="#!" class="dropdown-item">
                                    <i class="ti ti-clipboard-list"></i>
                                    <span>No. Control: 21590477</span>
                                </a>

                            </div>
                            <div class="tab-pane fade" id="drp-tab-2" role="tabpanel" aria-labelledby="drp-t2" tabindex="0">
                                <a href="#!" class="dropdown-item">
                                    <i class="ti ti-help"></i>
                                    <span>Support</span>
                                </a>
                                <a href="#!" class="dropdown-item">
                                    <i class="ti ti-user"></i>
                                    <span>Account Settings</span>
                                </a>
                                <a href="#!" class="dropdown-item">
                                    <i class="ti ti-lock"></i>
                                    <span>Privacy Center</span>
                                </a>
                                <a href="#!" class="dropdown-item">
                                    <i class="ti ti-messages"></i>
                                    <span>Feedback</span>
                                </a>
                                <a href="#!" class="dropdown-item">
                                    <i class="ti ti-list"></i>
                                    <span>History</span>
                                </a>
                            </div>
                        </div>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</header>
<!-- [ Header ] end -->



<!-- [ Main Content ] start -->
<div class="pc-container">
    <div class="pc-content">
        <!-- [ breadcrumb ] start -->
        <div class="page-header">
            <div class="page-block">
                <div class="row align-items-center">
                    <div class="col-md-12">
<!--                        <div class="page-header-title">-->
<!--                            <h5 class="m-b-10">Home</h5>-->
<!--                        </div>-->
                        <ul class="breadcrumb">
<!--                            <li class="breadcrumb-item"><a href="../dashboard/index.html">Inicio</a></li>-->
                            <li class="breadcrumb-item"><a href="<?= URL_APP ?>inicio">Dashboard</a></li>
<!--                            <li class="breadcrumb-item" aria-current="page">Home</li>-->
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <!-- [ breadcrumb ] end -->
        <!-- [ Main Content ] start -->
        <!-- body -->
        <div class="box-body">
            <?php View::content() ?>
        </div>

    </div>
</div>
<!-- [ Main Content ] end -->
<footer class="pc-footer">
    <div class="footer-wrapper container-fluid">
        <div class="row">
            <div class="col-sm my-1">
                <a href='https://wiki.kumbiaphp.com/Team_Development_KumbiaPHP_Framework'>© <?= date('Y'); ?> KumbiaPHP Team</a>
                <p class="m-0">Yara Fernanda Juárez Gómez</p>
            </div>
            <div class="col-auto my-1">
                <ul class="list-inline footer-link mb-0">
                    <li class="list-inline-item"><a href="<?= PUBLIC_PATH ?>login">Home</a></li>
<!--                    http://localhost:81/kumbiaphp/login-->
                </ul>
            </div>
        </div>
    </div>
</footer>

<!-- [Page Specific JS] start -->
<script src="<?=URL_APP?>libs/mantis/dist/assets/js/plugins/apexcharts.min.js"></script>
<script src="<?=URL_APP?>libs/mantis/dist/assets/js/pages/dashboard-default.js"></script>
<!-- [Page Specific JS] end -->

<!-- Required Js -->
<script src="<?=URL_APP?>libs/mantis/dist/assets/js/plugins/popper.min.js"></script>
<script src="<?=URL_APP?>libs/mantis/dist/assets/js/plugins/simplebar.min.js"></script>
<script src="<?=URL_APP?>libs/mantis/dist/assets/js/plugins/bootstrap.min.js"></script>
<script src="<?=URL_APP?>libs/mantis/dist/assets/js/fonts/custom-font.js"></script>
<script src="<?=URL_APP?>libs/mantis/dist/assets/js/pcoded.js"></script>
<script src="<?=URL_APP?>libs/mantis/dist/assets/js/plugins/feather.min.js"></script>

<script>layout_change('light');</script>
<script>change_box_container('false');</script>
<script>layout_rtl_change('false');</script>
<script>preset_change("preset-1");</script>
<script>font_change("Public-Sans");</script>

<!-- Tablas dinamicas -->
<script>
    let table = new DataTable('.myTable', {
        // config options...
    });
</script>

<!-- FilePond JS -->
<script src="https://unpkg.com/filepond/dist/filepond.js"></script>
<script>
    // Activar FilePond en todos los inputs tipo file
    FilePond.registerPlugin();
    FilePond.create(document.querySelector('.filepond'));
</script>

<!-- Select2 -->
<script>
    $(document).ready(function() {
        $('.js-example-basic-single').select2({
            width: '250px' // Define el ancho aquí
        });
    });
</script>



</body>

</html>
