<h1>Detalles_Ventas</h1>
<a href="<?= URL_APP ?>productos/registrar" class="btn btn-outline-success">
    Registrar <i class="fa-solid fa-pencil"></i>
</a>

<style>
    th, td {
        padding: 10px;
        text-align: left;
        border: 1px solid #ddd;
    }
</style>

<table class="table table-striped table-hover myTable">
    <thead>
    <tr>
        <th>ID</th>
        <th>Ventas_ID</th>
        <th>Producto</th>
        <th>Cantidad</th>
        <th>Subtotal</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($detalles_ventas as $p): ?>
        <tr>
            <td><?= Html::link("detalles/show/{$p->id}", "Ver", ["title" => "ir a detalles_venta", "class" => "btn btn-sm"]) ?></td>
            <td><?= $p->ventas_id ?></td>
            <td><?= $p->producto->nombre ?? 'Producto no disponible' ?></td>
            <td><?= $p->cantidad ?></td>
            <td><?= $p->subtotal ?></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
