<h1>Metodos de pago</h1>
<a href="<?= URL_APP ?>productos/registrar" class="btn btn-outline-success">Registrar <i class="fa-solid fa-pencil"></i></a>

<style>
    th, td {
        padding: 10px; /* Espacio dentro de las celdas */
        text-align: left; /* Alineación del texto */
        border: 1px solid #ddd; /* Borde para las celdas */
    }
</style>
<table class="table table-striped table-hover myTable">
    <thead>
    <tr>
        <th>ID</th>
        <th>Nombre</th>
    </tr>

    </thead>

    <tbody>
    <?php foreach ($metodos as $p):?>
        <tr>
            <td><?=Html::link("metodos/show/{$p->id}","Ver",["title"=>"ir a metodos_pago","class"=>"btn btn-sm"])?></td>
            <td><?=$p->nombre?></td>
        </tr>
    <?php endforeach; ?>


    </tbody>

</table>